# Generated by Django 6.0 on 2026-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="cases/", verbose_name="照片"
            ),
        ),
    ]
